spring.application.name=client-app
server.port=8073
kms.server.url=http://localhost:8074
kms.server.token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjg3NzQ5MDYyLCJleHAiOjE2ODc3NTI2NjIsInVzZXJJZCI6InRlc3QiLCJ1c2VyTmFtZSI6InRlc3QiLCJyb2xlcyI6WyJVU0VSIl19.4k7r8XqjW7x5n8zFfG9V5g