# Enable Emulator Connection
spring.cloud.gcp.spanner.emulator.enabled=true
spring.cloud.gcp.spanner.emulator-host=localhost:9010

# Mock instance details (Emulator will hold these in volatile memory)
spring.cloud.gcp.project-id=pxp-bdp-dev
spring.cloud.gcp.spanner.instance-id=keymaker-spanner
spring.cloud.gcp.spanner.database=keymaker-db